void print_int(void *n);
void print_float(void *f);
void print_char(void *c);
void print_string(void *s);
bool find_int(void *search, void *node_data);
bool find_float(void *search, void *node_data);
bool find_char(void *search, void *node_data);
bool find_string(void *search, void *node_data);
void copy_by_byte(Node **node, void *new_data, size_t data_size);
void free_node(Node *node);
