int convert_to_int(void *input, int (* fptr)(void *input));
int convert_to_longlong(void *input, long long int (* fptr)(void *input));
int string_to_int(void *input);
long long int string_to_longlong(void *input);
int char_to_int(void *input);
int float_to_int(void *input);
int lower_char_to_index(void *input);
int upper_char_to_index(void *input);
char convert_to_char(void *input, char (* fptr)(void *input));
char int_to_char(void *input);
char float_to_char(void *input);
char index_to_lower_char(void *input);
char index_to_upper_char(void *input);
int to_int(void *x);
char to_char(void *x);
char *to_string(void *x);
